### ISSUE TITLE
Possibility to use support.v4.app.DialogFragment

### ISSUE THREAD

**Issue by Tangomajom** [svenwiegand/time-duration-picker#2]
Hi, 

At first, thank you for uploading it, it is a nice component, it saved a lot of time for me. However in my app I'm using supportDialogs and fragments, and I would be good if I can avoid to rewrite my whole application.
Do you have any objections to use support.v4.app.DialogFragment instead of app.DialogFragment? 
If there's no any, could you please change your part in here? 

Thank you in advance, 

Tamás Oarga

**Comment by svenwiegand** [comment]
Sorry for the late reply. My podcast player [uPod](https://play.google.com/store/apps/details?id=mobi.upod.app) for which I wrote this component uses `minSdkVersion 14` and thus the platform's native `Fragment` implementation. Unfortunately using `support.v4.app.DialogFragment` would make the lib incompatible with uPod, so that I can't change this. 

So I guess you have to fork your own version and adjust it to use `support.v4.app.DialogFragment` which should be easy.

**Comment by kapalex** [comment]
Probably irrelevant but I've made a fork that adds the support for v4 support library, in addition to making the picker not get messed up with rtl languages
